// Generated by tools/ml/train_rhythm.py. Do not edit by hand.
// Logistic regression, irregular (AF-like) vs regular rhythm, on 5
// features of the last RR_WINDOW beat intervals. Scaler folded in.
// Held-out records, per window at p >= 0.5: accuracy 0.9618,
// sensitivity 0.9511, specificity 0.9711; AUC 0.9893.
#pragma once
#include <stdint.h>

#define RHYTHM_N_FEATURES 5
// Features: cv, rmssd_n, pnn50, medad_n, tpr
static const float RHYTHM_W[RHYTHM_N_FEATURES] = {19.196512f, -13.632301f, 8.3966268f, 14.058973f, -1.6817799f};
static const float RHYTHM_B = -5.2401204f;

// Self-test: RR windows (ms) with the probability this script computed.
// The firmware recomputes them at boot (features + model).
#define RHYTHM_N_TESTS 5
#define RHYTHM_TEST_LEN 30
static const uint16_t RHYTHM_TEST_RR[RHYTHM_N_TESTS][RHYTHM_TEST_LEN] = {
  {800, 804, 796, 787, 793, 785, 801, 820, 793, 791, 807, 805, 802, 786, 800, 810, 780, 793, 771, 781, 772, 796, 781, 804, 802, 797, 762, 792, 799, 802},
  {619, 640, 630, 634, 671, 634, 649, 668, 638, 648, 652, 651, 625, 652, 677, 619, 667, 652, 637, 690, 665, 626, 651, 662, 646, 664, 649, 663, 679, 636},
  {733, 626, 720, 510, 607, 669, 844, 883, 488, 573, 804, 381, 626, 684, 901, 810, 648, 641, 660, 944, 632, 651, 756, 681, 668, 522, 698, 629, 887, 804},
  {845, 997, 775, 1081, 849, 978, 566, 926, 479, 402, 783, 652, 886, 1344, 667, 713, 895, 958, 811, 805, 1005, 964, 623, 833, 858, 618, 907, 661, 1064, 892},
  {820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800, 820, 800},
};
static const float RHYTHM_TEST_P[RHYTHM_N_TESTS] = {0.0021803074f, 0.0043311168f, 0.9450052f, 0.98681788f, 0.0012612736f};
